name = "KG Minecraft Modpack"
author = "KG"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cafeb612f92b9bdfb351a2777a7798ea02ee0fc6f1d151b501ae0618f619906c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"

[options]
acceptable-game-versions = ["1.21.1"]
