name = "KG Server Pack"
author = "KG"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f3b9f0ab4b139bb5f0e0d0a5fd8ad4f9d057558106e60988c689e8a6e7f2d3a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"

[options]
acceptable-game-versions = ["1.21.1"]
