name = "KG Minecraft Modpack"
author = "KG"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb00bcd05585d8ffe73c78b6185bec6fa7ed16b760f5a8ad91b3c69628c91b7d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"

[options]
acceptable-game-versions = ["1.21.1"]
